// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "ScallyKit",
    platforms: [.iOS(.v18), .macOS(.v14)],
    products: [
        .library(name: "ScallyKit", targets: ["ScallyKit"])
    ],
    targets: [
        .target(
            name: "ScallyKit",
            resources: [
                .copy("Resources/RealESRGANx4.mlpackage"),
                // One-step diffusion. 461MB total, so these are gitignored and
                // regenerated by tools/convert_rsd.py and tools/convert_vae.py.
                .copy("Resources/RSD4x.mlpackage"),
                .copy("Resources/VQEncoder.mlpackage"),
                .copy("Resources/VQDecoder.mlpackage"),
            ]
        ),
        .testTarget(name: "ScallyKitTests", dependencies: ["ScallyKit"])
    ]
)
